### ISSUE TITLE
[1.19.4]crashed when a world finish loading

### ISSUE THREAD

**Issue by feiudfyg** [bl4ckscor3/SnowUnderTrees#8] opened 2023-05-01 07:09 UTC
the bug appeared on "https://github.com/mineblock11/snow-under-trees-fabric", a fork of this project.
the original project (this project) is not tested,but i think the issue should be reported here

### the mod caused Minecraft to crash when the world finish loading
it seems to be a render thread error
[crash-2023-05-01_14.57.08-client.txt](https://github.com/bl4ckscor3/SnowUnderTrees/files/11364049/crash-2023-05-01_14.57.08-client.txt)
here is the crash report

[2023-05-01-7.log](https://github.com/bl4ckscor3/SnowUnderTrees/files/11364056/2023-05-01-7.log)
here is the log

your project is really great, but it will be greater without this bug!

**Comment by feiudfyg** [comment] 2023-05-01 07:11
btw the fork is **Fabric** version

**Comment by bl4ckscor3** [comment] 2023-05-01 09:02
1. The crash you sent happens during rendering, but Snow Under Trees is a server side mod.
2. Please report crashes in a fork or port to that fork or port first, and let the author decide whether the issue needs to be reported upstream as well or not. The fork or port may be doing something different to the original, and the issue may not even appear in the original. You wouldn't tune your car, then go to your car dealer instead of the mechanic when something goes wrong with the tuned parts.

Closing as not caused by and not relevant to SUT.

**Closed as not planned by bl4ckscor3** 2023-05-01 09:02 UTC
Labels: invalid

**Comment by feiudfyg** [comment] 2023-05-01 10:37
thanks for your patient and I am sorry for reporting bugs of the fork project on this repo.
