### ISSUE TITLE
not working on 1.20, not generating snow under trees

### ISSUE THREAD

**Issue by Mrnar1s** [bl4ckscor3/SnowUnderTrees#10] opened 2023-07-04 20:43 UTC

**Comment by bl4ckscor3** [comment] 2023-07-04 20:56
The mod works just fine for me. I need more information than that. What other mods are you using? In which biome does this issue occur?

**Comment by bl4ckscor3** [comment] 2024-05-06 15:20
Looks to be a duplicate of #11, with the same fix.

**Closed as completed by bl4ckscor3** 2024-05-06 15:20 UTC
